FROM python:3.8.3-alpine
COPY . /app
WORKDIR /app

RUN apk update
RUN apk add bash
RUN apk add curl
RUN apk add g++
RUN apk add --no-cache unixodbc-dev
RUN pip3 install -r requirements.txt

#Download the desired package(s)
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.5.2.2-1_amd64.apk
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.5.2.1-1_amd64.apk

#Install the package(s)
RUN apk add --allow-untrusted msodbcsql17_17.5.2.2-1_amd64.apk
RUN apk add --allow-untrusted mssql-tools_17.5.2.1-1_amd64.apk

EXPOSE 8080/tcp
CMD ["python", "api.py"]